$(shell mkdir -p /home/jenkins/slaves/workspace/Grace_China_MP_ANDROID/android_code/device/hisi/customize/build_script/../../../../out/target/product/GRACE/obj/KERNEL_OBJ/arch/arm64/boot/dts/auto-generate/hi3635)
include /home/jenkins/slaves/workspace/Grace_China_MP_ANDROID/android_code/device/hisi/customize/build_script/../../../../kernel/arch/arm64/boot/dts/auto-generate/hi3635/hi3635_dtb.mk
dtbs: hi3635_dtb
